experiment_name: example_rnn
mode: validate # Mode to run the script: 'train' or 'validate'.
model_type: rnn
dataset:
  ticker: "ZC=F"
  start_date_train: "2000-08-01"
  corn_end_date_train: "2025-01-01"
  weather_end_date_train: "2024-12-31"
  start_date_test: "2025-01-01"
  corn_end_date_test: "2025-03-31"
  weather_end_date_test: "2025-03-30"

  features:
    - Close
    - MA_7
    - MA_30
    - shortwave_radiation_sum
    - temperature_2m_mean
    - sunshine_duration
    - precipitation_sum
    - precipitation_hours

training:
  sequence_length: 30 # Length of input sequences.
  hidden_size: 64 # Number of features in the hidden state.
  num_layers: 2 # Dimension of the encoding representations.
  num_epochs: 5 # Number of training epochs.
  learning_rate: 0.001  # Learning rate for the optimizer.
  n_splits: 9 # Number of splits for TimeSeriesSplit during validation.
